### ISSUE TITLE
Firebase Functions requires Node.js 10 or higher

### ISSUE THREAD

**Issue by kevinpthorne** [styrken/firebase-crashlytics-webhook#1]
Just gotta dust it off and upgrade it to at least Node 10. Currently working on it.

**Comment by kevinpthorne** [comment]
Just kidding. Google in their "infinite" wisdom (/s) removed Crashlytics from their Functions API. Ugh

**Comment by kevinpthorne** [comment]
To the poor soul who ends up here, sentry.io is a good looking alternative here.

**Comment by styrken** [comment]
HI @kevinpthorne, i have updated the readme with the sentry link.
